# Generated by Django 5.1.9 on 2025-05-19 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время создания')),
                ('admin_telegram_id', models.CharField(max_length=64, verbose_name='ID админа Telegram')),
                ('user_telegram_id', models.CharField(max_length=64, verbose_name='ID пользователя Telegram')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма заказа')),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='producers/', verbose_name='Логотип')),
                ('hidden', models.BooleanField(default=False, verbose_name='Скрыт')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип сорта')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('characteristics', models.TextField(blank=True, verbose_name='Характеристики')),
                ('hidden', models.BooleanField(default=False, verbose_name='Скрыт')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.producer', verbose_name='Сидбанк')),
                ('photos', models.ManyToManyField(blank=True, to='store.productphoto', verbose_name='Фотографии')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.type', verbose_name='Тип сорта')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seeds_count', models.CharField(max_length=20, verbose_name='Количество семян (фасовка)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за пачку')),
                ('stock', models.PositiveIntegerField(verbose_name='Количество на складе')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='store.product', verbose_name='Сорт')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_snapshot', models.CharField(max_length=255, verbose_name='Название сорта (снимок)')),
                ('seeds_count_snapshot', models.CharField(max_length=20, verbose_name='Фасовка (снимок)')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество упаковок')),
                ('price_snapshot', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за упаковку (снимок)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product', verbose_name='Сорт')),
                ('product_package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.productpackage', verbose_name='Фасовка')),
            ],
        ),
    ]
